# Generated by Django 5.1.5 on 2025-01-17 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField()),
                ('year', models.IntegerField()),
                ('monto_dos_dias', models.IntegerField()),
                ('monto_tres_dias', models.IntegerField()),
                ('monto_cuatro_dias', models.IntegerField()),
                ('monto_cinco_dias', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('fecha_inicio_gym', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('agregado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuotaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagada', models.BooleanField(default=False)),
                ('descuento', models.IntegerField(default=0)),
                ('dias_por_semana', models.IntegerField(choices=[(2, '2 días'), (3, '3 días'), (4, '4 días'), (5, '5 días')])),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_vencimiento_cuota', models.DateField(blank=True, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alumno')),
                ('cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cuota')),
            ],
        ),
        migrations.AddField(
            model_name='alumno',
            name='cuotas',
            field=models.ManyToManyField(through='api.CuotaAlumno', to='api.cuota'),
        ),
    ]
