# Generated by Django 5.1.5 on 2025-02-12 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ejercicio_ejercicioalumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(1, 1, 1)),
        ),
        migrations.AddField(
            model_name='alumno',
            name='peso',
            field=models.FloatField(default=0),
        ),
    ]
