# Generated by Django 5.1.5 on 2025-02-13 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alumno_altura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='fecha_inicio_gym',
        ),
        migrations.AddField(
            model_name='alumno',
            name='ejercicios',
            field=models.ManyToManyField(through='api.EjercicioAlumno', to='api.ejercicio'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='ejercicioalumno',
            name='peso_repeticion_maxima',
            field=models.IntegerField(default=0),
        ),
    ]
