# Generated by Django 5.1.5 on 2025-02-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_alumno_fecha_inicio_gym_alumno_ejercicios_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cuotaalumno',
            old_name='dias_por_semana',
            new_name='plan',
        ),
        migrations.AddField(
            model_name='cuota',
            name='month',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='cuota',
            name='year',
            field=models.IntegerField(default=2025),
        ),
    ]
