# Generated by Django 5.1.5 on 2025-02-15 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_dias_por_semana_cuotaalumno_plan_cuota_month_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuota',
            unique_together={('year', 'month')},
        ),
        migrations.RemoveField(
            model_name='cuota',
            name='fecha',
        ),
    ]
