# Generated by Django 5.1.5 on 2025-02-18 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_cuota_unique_together_remove_cuota_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuotaalumno',
            name='monto_pagado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
