# Generated by Django 5.1.5 on 2025-03-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_cuotaalumno_monto_pagado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicioalumno',
            name='peso_repeticion_maxima',
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='ejercicios/'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='month',
            field=models.IntegerField(default=3),
        ),
    ]
