# Generated by Django 5.1.5 on 2025-03-06 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_ejercicioalumno_peso_repeticion_maxima_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ejercicioalumno',
            old_name='peso',
            new_name='peso_repeticion_maxima',
        ),
        migrations.RemoveField(
            model_name='ejercicioalumno',
            name='repeticiones',
        ),
        migrations.RemoveField(
            model_name='ejercicioalumno',
            name='series',
        ),
    ]
