version: "3.8"

services:
  web:
    build: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - django_data:/app/backend/db
      - django_media:/app/backend/media
    environment:
      - DEBUG=0
      - SECRET_KEY=${DJANGO_SECRET_KEY:-mysecretkey}
      - DJANGO_SETTINGS_MODULE=backend.settings_prod
    command: gunicorn --bind 0.0.0.0:8000 backend.wsgi:application

  # Uncomment the following if you need a separate database
  # db:
  #   image: postgres:14-alpine
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data/
  #   environment:
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
  #     - POSTGRES_USER=${POSTGRES_USER:-postgres}
  #     - POSTGRES_DB=${POSTGRES_DB:-django_db}
  #   restart: always

volumes:
  django_data:
  django_media:
  # postgres_data:
